// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

type AuditLog struct {
	ID     int64  `json:"id"`
	At     int64  `json:"at"`
	Tbl    string `json:"tbl"`
	Op     string `json:"op"`
	Key    string `json:"key"`
	Detail string `json:"detail"`
}

type Deploy struct {
	ID         int64  `json:"id"`
	Project    string `json:"project"`
	CommitSha  string `json:"commit_sha"`
	Trigger    string `json:"trigger"`
	Images     string `json:"images"`
	SnapshotID int64  `json:"snapshot_id"`
	RestoredID int64  `json:"restored_id"`
	Undoes     int64  `json:"undoes"`
	Result     string `json:"result"`
	Error      string `json:"error"`
	Summary    string `json:"summary"`
	StartedAt  int64  `json:"started_at"`
	FinishedAt int64  `json:"finished_at"`
	BeforeID   int64  `json:"before_id"`
	Parts      string `json:"parts"`
}

type Env struct {
	Project   string `json:"project"`
	Key       string `json:"key"`
	Value     []byte `json:"value"`
	UpdatedAt int64  `json:"updated_at"`
}

type Event struct {
	ID      int64  `json:"id"`
	At      int64  `json:"at"`
	Project string `json:"project"`
	Kind    string `json:"kind"`
	Message string `json:"message"`
}

type Meta struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Pin struct {
	Project      string `json:"project"`
	Service      string `json:"service"`
	Image        string `json:"image"`
	Digest       string `json:"digest"`
	ComposeImage string `json:"compose_image"`
	DeployID     int64  `json:"deploy_id"`
	CreatedAt    int64  `json:"created_at"`
}

type Preview struct {
	Project    string `json:"project"`
	Name       string `json:"name"`
	Ref        string `json:"ref"`
	CommitSha  string `json:"commit_sha"`
	Images     string `json:"images"`
	SnapshotID int64  `json:"snapshot_id"`
	Data       string `json:"data"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
	DeployID   int64  `json:"deploy_id"`
}

type Project struct {
	Path      string `json:"path"`
	Disabled  bool   `json:"disabled"`
	CommitSha string `json:"commit_sha"`
	AppliedAt int64  `json:"applied_at"`
	Limits    string `json:"limits"`
}

type Session struct {
	IDHash  string `json:"id_hash"`
	User    string `json:"user"`
	Expires int64  `json:"expires"`
}

type Snapshot struct {
	ID        int64  `json:"id"`
	Project   string `json:"project"`
	Reason    string `json:"reason"`
	Note      string `json:"note"`
	CommitSha string `json:"commit_sha"`
	CreatedAt int64  `json:"created_at"`
}

type SnapshotVolume struct {
	SnapshotID int64  `json:"snapshot_id"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
	Source     string `json:"source"`
	Path       string `json:"path"`
}

type User struct {
	Name      string `json:"name"`
	Role      string `json:"role"`
	Global    bool   `json:"global"`
	Secret    string `json:"secret"`
	CreatedAt int64  `json:"created_at"`
}

type UserRepo struct {
	User string `json:"user"`
	Repo string `json:"repo"`
}
