// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

type AuditLog struct {
	ID     int64  `json:"id"`
	At     int64  `json:"at"`
	Tbl    string `json:"tbl"`
	Op     string `json:"op"`
	Key    string `json:"key"`
	Detail string `json:"detail"`
}

type Env struct {
	Project   string `json:"project"`
	Key       string `json:"key"`
	Value     []byte `json:"value"`
	UpdatedAt int64  `json:"updated_at"`
}

type Event struct {
	ID      int64  `json:"id"`
	At      int64  `json:"at"`
	Project string `json:"project"`
	Kind    string `json:"kind"`
	Message string `json:"message"`
}

type Meta struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Preview struct {
	Project    string `json:"project"`
	Name       string `json:"name"`
	Ref        string `json:"ref"`
	CommitSha  string `json:"commit_sha"`
	Images     string `json:"images"`
	SnapshotID int64  `json:"snapshot_id"`
	Data       string `json:"data"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type Project struct {
	Path      string `json:"path"`
	Disabled  bool   `json:"disabled"`
	CommitSha string `json:"commit_sha"`
	AppliedAt int64  `json:"applied_at"`
}

type Session struct {
	IDHash  string `json:"id_hash"`
	Expires int64  `json:"expires"`
}

type Snapshot struct {
	ID        int64  `json:"id"`
	Project   string `json:"project"`
	Reason    string `json:"reason"`
	Note      string `json:"note"`
	CommitSha string `json:"commit_sha"`
	CreatedAt int64  `json:"created_at"`
}

type SnapshotVolume struct {
	SnapshotID int64  `json:"snapshot_id"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
	Source     string `json:"source"`
	Path       string `json:"path"`
}

type User struct {
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
	Pattern   string `json:"pattern"`
	Repos     string `json:"repos"`
	CreatedAt int64  `json:"created_at"`
}
