// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
)

const addSnapshotVolume = `-- name: AddSnapshotVolume :exec
INSERT INTO snapshot_volumes (snapshot_id, kind, name, source, path) VALUES (?, ?, ?, ?, ?)
`

type AddSnapshotVolumeParams struct {
	SnapshotID int64  `json:"snapshot_id"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
	Source     string `json:"source"`
	Path       string `json:"path"`
}

func (q *Queries) AddSnapshotVolume(ctx context.Context, arg AddSnapshotVolumeParams) error {
	_, err := q.db.ExecContext(ctx, addSnapshotVolume,
		arg.SnapshotID,
		arg.Kind,
		arg.Name,
		arg.Source,
		arg.Path,
	)
	return err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (at, project, kind, message) VALUES (?, ?, ?, ?)
`

type CreateEventParams struct {
	At      int64  `json:"at"`
	Project string `json:"project"`
	Kind    string `json:"kind"`
	Message string `json:"message"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.At,
		arg.Project,
		arg.Kind,
		arg.Message,
	)
	return err
}

const createOrReplaceUser = `-- name: CreateOrReplaceUser :exec
INSERT INTO users (name, token_hash, pattern, repos, created_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (name) DO UPDATE SET token_hash = excluded.token_hash, pattern = excluded.pattern, repos = excluded.repos
`

type CreateOrReplaceUserParams struct {
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
	Pattern   string `json:"pattern"`
	Repos     string `json:"repos"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateOrReplaceUser(ctx context.Context, arg CreateOrReplaceUserParams) error {
	_, err := q.db.ExecContext(ctx, createOrReplaceUser,
		arg.Name,
		arg.TokenHash,
		arg.Pattern,
		arg.Repos,
		arg.CreatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id_hash, expires) VALUES (?, ?)
`

type CreateSessionParams struct {
	IDHash  string `json:"id_hash"`
	Expires int64  `json:"expires"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.IDHash, arg.Expires)
	return err
}

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO snapshots (project, reason, note, commit_sha, created_at) VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateSnapshotParams struct {
	Project   string `json:"project"`
	Reason    string `json:"reason"`
	Note      string `json:"note"`
	CommitSha string `json:"commit_sha"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSnapshot,
		arg.Project,
		arg.Reason,
		arg.Note,
		arg.CommitSha,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAllSessions = `-- name: DeleteAllSessions :exec
DELETE FROM sessions
`

func (q *Queries) DeleteAllSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSessions)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expires int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expires)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE path = ?
`

func (q *Queries) DeleteProject(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, path)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, idHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, idHash)
	return err
}

const deleteSnapshot = `-- name: DeleteSnapshot :exec
DELETE FROM snapshots WHERE id = ?
`

func (q *Queries) DeleteSnapshot(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSnapshot, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE name = ?
`

func (q *Queries) DeleteUser(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, name)
	return err
}

const getMeta = `-- name: GetMeta :one
SELECT value FROM meta WHERE key = ?
`

func (q *Queries) GetMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getSessionExpiry = `-- name: GetSessionExpiry :one
SELECT expires FROM sessions WHERE id_hash = ?
`

func (q *Queries) GetSessionExpiry(ctx context.Context, idHash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSessionExpiry, idHash)
	var expires int64
	err := row.Scan(&expires)
	return expires, err
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT id, project, reason, note, commit_sha, created_at FROM snapshots WHERE id = ?
`

func (q *Queries) GetSnapshot(ctx context.Context, id int64) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshot, id)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.Reason,
		&i.Note,
		&i.CommitSha,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT name, token_hash, pattern, repos, created_at FROM users WHERE name = ?
`

func (q *Queries) GetUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, name)
	var i User
	err := row.Scan(
		&i.Name,
		&i.TokenHash,
		&i.Pattern,
		&i.Repos,
		&i.CreatedAt,
	)
	return i, err
}

const listAudit = `-- name: ListAudit :many
SELECT id, at, tbl, op, "key", detail FROM audit_log ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListAudit(ctx context.Context, limit int64) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Tbl,
			&i.Op,
			&i.Key,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoSnapshotsToPrune = `-- name: ListAutoSnapshotsToPrune :many
SELECT id, project, reason, note, commit_sha, created_at FROM snapshots
WHERE project = ?1 AND reason != 'manual'
ORDER BY id DESC LIMIT -1 OFFSET ?2
`

type ListAutoSnapshotsToPruneParams struct {
	Project string `json:"project"`
	Keep    int64  `json:"keep"`
}

// automatic snapshots (not manual) of a project beyond the newest `keep`
func (q *Queries) ListAutoSnapshotsToPrune(ctx context.Context, arg ListAutoSnapshotsToPruneParams) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listAutoSnapshotsToPrune, arg.Project, arg.Keep)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.Reason,
			&i.Note,
			&i.CommitSha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnv = `-- name: ListEnv :many
SELECT key, value FROM env WHERE project = ?
`

type ListEnvRow struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) ListEnv(ctx context.Context, project string) ([]ListEnvRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnv, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvRow{}
	for rows.Next() {
		var i ListEnvRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvKeys = `-- name: ListEnvKeys :many
SELECT key, updated_at FROM env WHERE project = ? ORDER BY key
`

type ListEnvKeysRow struct {
	Key       string `json:"key"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) ListEnvKeys(ctx context.Context, project string) ([]ListEnvKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnvKeys, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvKeysRow{}
	for rows.Next() {
		var i ListEnvKeysRow
		if err := rows.Scan(&i.Key, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, at, project, kind, message FROM events
WHERE ?1 = '' OR project = ?1
ORDER BY id DESC LIMIT ?2
`

type ListEventsParams struct {
	Project interface{} `json:"project"`
	Lim     int64       `json:"lim"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.Project, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Project,
			&i.Kind,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT path, disabled, commit_sha, applied_at FROM projects ORDER BY path
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.Path,
			&i.Disabled,
			&i.CommitSha,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotVolumes = `-- name: ListSnapshotVolumes :many
SELECT snapshot_id, kind, name, source, path FROM snapshot_volumes WHERE snapshot_id = ? ORDER BY name
`

func (q *Queries) ListSnapshotVolumes(ctx context.Context, snapshotID int64) ([]SnapshotVolume, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotVolumes, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SnapshotVolume{}
	for rows.Next() {
		var i SnapshotVolume
		if err := rows.Scan(
			&i.SnapshotID,
			&i.Kind,
			&i.Name,
			&i.Source,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT id, project, reason, note, commit_sha, created_at FROM snapshots
WHERE ?1 = '' OR project = ?1
ORDER BY id DESC
`

func (q *Queries) ListSnapshots(ctx context.Context, project interface{}) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshots, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.Reason,
			&i.Note,
			&i.CommitSha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT name, token_hash, pattern, repos, created_at FROM users ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Name,
			&i.TokenHash,
			&i.Pattern,
			&i.Repos,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEnv = `-- name: SetEnv :exec
INSERT INTO env (project, key, value, updated_at) VALUES (?, ?, ?, ?)
ON CONFLICT (project, key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type SetEnvParams struct {
	Project   string `json:"project"`
	Key       string `json:"key"`
	Value     []byte `json:"value"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) SetEnv(ctx context.Context, arg SetEnvParams) error {
	_, err := q.db.ExecContext(ctx, setEnv,
		arg.Project,
		arg.Key,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}

const setMeta = `-- name: SetMeta :exec
INSERT INTO meta (key, value) VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type SetMetaParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetMeta(ctx context.Context, arg SetMetaParams) error {
	_, err := q.db.ExecContext(ctx, setMeta, arg.Key, arg.Value)
	return err
}

const setProjectApplied = `-- name: SetProjectApplied :exec
INSERT INTO projects (path, commit_sha, applied_at) VALUES (?, ?, ?)
ON CONFLICT (path) DO UPDATE SET commit_sha = excluded.commit_sha, applied_at = excluded.applied_at
`

type SetProjectAppliedParams struct {
	Path      string `json:"path"`
	CommitSha string `json:"commit_sha"`
	AppliedAt int64  `json:"applied_at"`
}

func (q *Queries) SetProjectApplied(ctx context.Context, arg SetProjectAppliedParams) error {
	_, err := q.db.ExecContext(ctx, setProjectApplied, arg.Path, arg.CommitSha, arg.AppliedAt)
	return err
}

const setProjectDisabled = `-- name: SetProjectDisabled :exec
INSERT INTO projects (path, disabled) VALUES (?, ?)
ON CONFLICT (path) DO UPDATE SET disabled = excluded.disabled
`

type SetProjectDisabledParams struct {
	Path     string `json:"path"`
	Disabled bool   `json:"disabled"`
}

func (q *Queries) SetProjectDisabled(ctx context.Context, arg SetProjectDisabledParams) error {
	_, err := q.db.ExecContext(ctx, setProjectDisabled, arg.Path, arg.Disabled)
	return err
}

const unsetEnv = `-- name: UnsetEnv :exec
DELETE FROM env WHERE project = ? AND key = ?
`

type UnsetEnvParams struct {
	Project string `json:"project"`
	Key     string `json:"key"`
}

func (q *Queries) UnsetEnv(ctx context.Context, arg UnsetEnvParams) error {
	_, err := q.db.ExecContext(ctx, unsetEnv, arg.Project, arg.Key)
	return err
}

const updateUserRules = `-- name: UpdateUserRules :execrows
UPDATE users SET pattern = ?, repos = ? WHERE name = ?
`

type UpdateUserRulesParams struct {
	Pattern string `json:"pattern"`
	Repos   string `json:"repos"`
	Name    string `json:"name"`
}

func (q *Queries) UpdateUserRules(ctx context.Context, arg UpdateUserRulesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserRules, arg.Pattern, arg.Repos, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
