// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
)

const addSnapshotVolume = `-- name: AddSnapshotVolume :exec
INSERT INTO snapshot_volumes (snapshot_id, kind, name, source, path) VALUES (?, ?, ?, ?, ?)
`

type AddSnapshotVolumeParams struct {
	SnapshotID int64  `json:"snapshot_id"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
	Source     string `json:"source"`
	Path       string `json:"path"`
}

func (q *Queries) AddSnapshotVolume(ctx context.Context, arg AddSnapshotVolumeParams) error {
	_, err := q.db.ExecContext(ctx, addSnapshotVolume,
		arg.SnapshotID,
		arg.Kind,
		arg.Name,
		arg.Source,
		arg.Path,
	)
	return err
}

const addUserRepo = `-- name: AddUserRepo :exec
INSERT INTO user_repos (user, repo) VALUES (?, ?)
`

type AddUserRepoParams struct {
	User string `json:"user"`
	Repo string `json:"repo"`
}

func (q *Queries) AddUserRepo(ctx context.Context, arg AddUserRepoParams) error {
	_, err := q.db.ExecContext(ctx, addUserRepo, arg.User, arg.Repo)
	return err
}

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM users WHERE role = 'admin'
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeploy = `-- name: CreateDeploy :one
INSERT INTO deploys (project, commit_sha, trigger, images, snapshot_id, restored_id, undoes, before_id, parts, result, error, summary, started_at, finished_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateDeployParams struct {
	Project    string `json:"project"`
	CommitSha  string `json:"commit_sha"`
	Trigger    string `json:"trigger"`
	Images     string `json:"images"`
	SnapshotID int64  `json:"snapshot_id"`
	RestoredID int64  `json:"restored_id"`
	Undoes     int64  `json:"undoes"`
	BeforeID   int64  `json:"before_id"`
	Parts      string `json:"parts"`
	Result     string `json:"result"`
	Error      string `json:"error"`
	Summary    string `json:"summary"`
	StartedAt  int64  `json:"started_at"`
	FinishedAt int64  `json:"finished_at"`
}

func (q *Queries) CreateDeploy(ctx context.Context, arg CreateDeployParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDeploy,
		arg.Project,
		arg.CommitSha,
		arg.Trigger,
		arg.Images,
		arg.SnapshotID,
		arg.RestoredID,
		arg.Undoes,
		arg.BeforeID,
		arg.Parts,
		arg.Result,
		arg.Error,
		arg.Summary,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (at, project, kind, message) VALUES (?, ?, ?, ?)
`

type CreateEventParams struct {
	At      int64  `json:"at"`
	Project string `json:"project"`
	Kind    string `json:"kind"`
	Message string `json:"message"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.At,
		arg.Project,
		arg.Kind,
		arg.Message,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id_hash, user, expires) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	IDHash  string `json:"id_hash"`
	User    string `json:"user"`
	Expires int64  `json:"expires"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.IDHash, arg.User, arg.Expires)
	return err
}

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO snapshots (project, reason, note, commit_sha, created_at) VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateSnapshotParams struct {
	Project   string `json:"project"`
	Reason    string `json:"reason"`
	Note      string `json:"note"`
	CommitSha string `json:"commit_sha"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSnapshot,
		arg.Project,
		arg.Reason,
		arg.Note,
		arg.CommitSha,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (name, role, global, secret, created_at) VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Name      string `json:"name"`
	Role      string `json:"role"`
	Global    bool   `json:"global"`
	Secret    string `json:"secret"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.Role,
		arg.Global,
		arg.Secret,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expires int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expires)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePin = `-- name: DeletePin :execrows
DELETE FROM pins WHERE project = ? AND service = ?
`

type DeletePinParams struct {
	Project string `json:"project"`
	Service string `json:"service"`
}

func (q *Queries) DeletePin(ctx context.Context, arg DeletePinParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePin, arg.Project, arg.Service)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePreview = `-- name: DeletePreview :exec
DELETE FROM previews WHERE project = ? AND name = ?
`

type DeletePreviewParams struct {
	Project string `json:"project"`
	Name    string `json:"name"`
}

func (q *Queries) DeletePreview(ctx context.Context, arg DeletePreviewParams) error {
	_, err := q.db.ExecContext(ctx, deletePreview, arg.Project, arg.Name)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE path = ?
`

func (q *Queries) DeleteProject(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, path)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, idHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, idHash)
	return err
}

const deleteSnapshot = `-- name: DeleteSnapshot :exec
DELETE FROM snapshots WHERE id = ?
`

func (q *Queries) DeleteSnapshot(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSnapshot, id)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE name = ?
`

func (q *Queries) DeleteUser(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUserRepos = `-- name: DeleteUserRepos :exec
DELETE FROM user_repos WHERE user = ?
`

func (q *Queries) DeleteUserRepos(ctx context.Context, user string) error {
	_, err := q.db.ExecContext(ctx, deleteUserRepos, user)
	return err
}

const getDeploy = `-- name: GetDeploy :one
SELECT id, project, commit_sha, "trigger", images, snapshot_id, restored_id, undoes, result, error, summary, started_at, finished_at, before_id, parts FROM deploys WHERE id = ?
`

func (q *Queries) GetDeploy(ctx context.Context, id int64) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, getDeploy, id)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.CommitSha,
		&i.Trigger,
		&i.Images,
		&i.SnapshotID,
		&i.RestoredID,
		&i.Undoes,
		&i.Result,
		&i.Error,
		&i.Summary,
		&i.StartedAt,
		&i.FinishedAt,
		&i.BeforeID,
		&i.Parts,
	)
	return i, err
}

const getMeta = `-- name: GetMeta :one
SELECT value FROM meta WHERE key = ?
`

func (q *Queries) GetMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getPreview = `-- name: GetPreview :one
SELECT project, name, ref, commit_sha, images, snapshot_id, data, created_at, updated_at, deploy_id, services FROM previews WHERE project = ? AND name = ?
`

type GetPreviewParams struct {
	Project string `json:"project"`
	Name    string `json:"name"`
}

func (q *Queries) GetPreview(ctx context.Context, arg GetPreviewParams) (Preview, error) {
	row := q.db.QueryRowContext(ctx, getPreview, arg.Project, arg.Name)
	var i Preview
	err := row.Scan(
		&i.Project,
		&i.Name,
		&i.Ref,
		&i.CommitSha,
		&i.Images,
		&i.SnapshotID,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeployID,
		&i.Services,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT user, expires FROM sessions WHERE id_hash = ?
`

type GetSessionRow struct {
	User    string `json:"user"`
	Expires int64  `json:"expires"`
}

func (q *Queries) GetSession(ctx context.Context, idHash string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, idHash)
	var i GetSessionRow
	err := row.Scan(&i.User, &i.Expires)
	return i, err
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT id, project, reason, note, commit_sha, created_at FROM snapshots WHERE id = ?
`

func (q *Queries) GetSnapshot(ctx context.Context, id int64) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshot, id)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.Reason,
		&i.Note,
		&i.CommitSha,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT name, role, global, secret, created_at FROM users WHERE name = ?
`

func (q *Queries) GetUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, name)
	var i User
	err := row.Scan(
		&i.Name,
		&i.Role,
		&i.Global,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const insertEnvIfMissing = `-- name: InsertEnvIfMissing :execrows
INSERT INTO env (project, key, value, updated_at) VALUES (?, ?, ?, ?)
ON CONFLICT (project, key) DO NOTHING
`

type InsertEnvIfMissingParams struct {
	Project   string `json:"project"`
	Key       string `json:"key"`
	Value     []byte `json:"value"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) InsertEnvIfMissing(ctx context.Context, arg InsertEnvIfMissingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertEnvIfMissing,
		arg.Project,
		arg.Key,
		arg.Value,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const latestDeploys = `-- name: LatestDeploys :many
SELECT id, project, commit_sha, "trigger", images, snapshot_id, restored_id, undoes, result, error, summary, started_at, finished_at, before_id, parts FROM deploys WHERE id IN (SELECT max(id) FROM deploys GROUP BY project)
`

// the newest deploy of every project
func (q *Queries) LatestDeploys(ctx context.Context) ([]Deploy, error) {
	rows, err := q.db.QueryContext(ctx, latestDeploys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deploy{}
	for rows.Next() {
		var i Deploy
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.CommitSha,
			&i.Trigger,
			&i.Images,
			&i.SnapshotID,
			&i.RestoredID,
			&i.Undoes,
			&i.Result,
			&i.Error,
			&i.Summary,
			&i.StartedAt,
			&i.FinishedAt,
			&i.BeforeID,
			&i.Parts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllEnv = `-- name: ListAllEnv :many
SELECT project, key, value FROM env ORDER BY project, key
`

type ListAllEnvRow struct {
	Project string `json:"project"`
	Key     string `json:"key"`
	Value   []byte `json:"value"`
}

func (q *Queries) ListAllEnv(ctx context.Context) ([]ListAllEnvRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllEnv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllEnvRow{}
	for rows.Next() {
		var i ListAllEnvRow
		if err := rows.Scan(&i.Project, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudit = `-- name: ListAudit :many
SELECT id, at, tbl, op, "key", detail FROM audit_log ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListAudit(ctx context.Context, limit int64) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Tbl,
			&i.Op,
			&i.Key,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoSnapshotsToPrune = `-- name: ListAutoSnapshotsToPrune :many
SELECT id, project, reason, note, commit_sha, created_at FROM snapshots
WHERE project = ?1 AND reason NOT IN ('manual', 'upload')
ORDER BY id DESC LIMIT -1 OFFSET ?2
`

type ListAutoSnapshotsToPruneParams struct {
	Project string `json:"project"`
	Keep    int64  `json:"keep"`
}

// automatic snapshots (not manual or uploaded) of a project beyond the newest `keep`
func (q *Queries) ListAutoSnapshotsToPrune(ctx context.Context, arg ListAutoSnapshotsToPruneParams) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listAutoSnapshotsToPrune, arg.Project, arg.Keep)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.Reason,
			&i.Note,
			&i.CommitSha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploys = `-- name: ListDeploys :many
SELECT id, project, commit_sha, "trigger", images, snapshot_id, restored_id, undoes, result, error, summary, started_at, finished_at, before_id, parts FROM deploys WHERE project = ? ORDER BY id DESC LIMIT ?
`

type ListDeploysParams struct {
	Project string `json:"project"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) ListDeploys(ctx context.Context, arg ListDeploysParams) ([]Deploy, error) {
	rows, err := q.db.QueryContext(ctx, listDeploys, arg.Project, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deploy{}
	for rows.Next() {
		var i Deploy
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.CommitSha,
			&i.Trigger,
			&i.Images,
			&i.SnapshotID,
			&i.RestoredID,
			&i.Undoes,
			&i.Result,
			&i.Error,
			&i.Summary,
			&i.StartedAt,
			&i.FinishedAt,
			&i.BeforeID,
			&i.Parts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnv = `-- name: ListEnv :many
SELECT key, value FROM env WHERE project = ?
`

type ListEnvRow struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) ListEnv(ctx context.Context, project string) ([]ListEnvRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnv, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvRow{}
	for rows.Next() {
		var i ListEnvRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvKeys = `-- name: ListEnvKeys :many
SELECT key, updated_at FROM env WHERE project = ? ORDER BY key
`

type ListEnvKeysRow struct {
	Key       string `json:"key"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) ListEnvKeys(ctx context.Context, project string) ([]ListEnvKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnvKeys, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvKeysRow{}
	for rows.Next() {
		var i ListEnvKeysRow
		if err := rows.Scan(&i.Key, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, at, project, kind, message FROM events
WHERE (?1 = '' OR project = ?1) AND (?2 = 0 OR id < ?2)
ORDER BY id DESC LIMIT ?3
`

type ListEventsParams struct {
	Project interface{} `json:"project"`
	Before  interface{} `json:"before"`
	Lim     int64       `json:"lim"`
}

// newest first; before > 0 pages back (ids below it)
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.Project, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Project,
			&i.Kind,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPins = `-- name: ListPins :many
SELECT project, service, image, digest, compose_image, deploy_id, created_at FROM pins
WHERE ?1 = '' OR project = ?1
ORDER BY project, service
`

func (q *Queries) ListPins(ctx context.Context, project interface{}) ([]Pin, error) {
	rows, err := q.db.QueryContext(ctx, listPins, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pin{}
	for rows.Next() {
		var i Pin
		if err := rows.Scan(
			&i.Project,
			&i.Service,
			&i.Image,
			&i.Digest,
			&i.ComposeImage,
			&i.DeployID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviews = `-- name: ListPreviews :many
SELECT project, name, ref, commit_sha, images, snapshot_id, data, created_at, updated_at, deploy_id, services FROM previews
WHERE ?1 = '' OR project = ?1
ORDER BY project, name
`

func (q *Queries) ListPreviews(ctx context.Context, project interface{}) ([]Preview, error) {
	rows, err := q.db.QueryContext(ctx, listPreviews, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preview{}
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.Project,
			&i.Name,
			&i.Ref,
			&i.CommitSha,
			&i.Images,
			&i.SnapshotID,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeployID,
			&i.Services,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT path, disabled, commit_sha, applied_at, limits FROM projects ORDER BY path
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.Path,
			&i.Disabled,
			&i.CommitSha,
			&i.AppliedAt,
			&i.Limits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposOfUser = `-- name: ListReposOfUser :many
SELECT repo FROM user_repos WHERE user = ? ORDER BY repo
`

func (q *Queries) ListReposOfUser(ctx context.Context, user string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listReposOfUser, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var repo string
		if err := rows.Scan(&repo); err != nil {
			return nil, err
		}
		items = append(items, repo)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotVolumes = `-- name: ListSnapshotVolumes :many
SELECT snapshot_id, kind, name, source, path FROM snapshot_volumes WHERE snapshot_id = ? ORDER BY name
`

func (q *Queries) ListSnapshotVolumes(ctx context.Context, snapshotID int64) ([]SnapshotVolume, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotVolumes, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SnapshotVolume{}
	for rows.Next() {
		var i SnapshotVolume
		if err := rows.Scan(
			&i.SnapshotID,
			&i.Kind,
			&i.Name,
			&i.Source,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT id, project, reason, note, commit_sha, created_at FROM snapshots
WHERE ?1 = '' OR project = ?1
ORDER BY id DESC
`

func (q *Queries) ListSnapshots(ctx context.Context, project interface{}) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshots, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.Reason,
			&i.Note,
			&i.CommitSha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRepos = `-- name: ListUserRepos :many
SELECT user, repo FROM user_repos ORDER BY user, repo
`

func (q *Queries) ListUserRepos(ctx context.Context) ([]UserRepo, error) {
	rows, err := q.db.QueryContext(ctx, listUserRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRepo{}
	for rows.Next() {
		var i UserRepo
		if err := rows.Scan(&i.User, &i.Repo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT name, role, global, secret, created_at FROM users ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Name,
			&i.Role,
			&i.Global,
			&i.Secret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const previousDeploy = `-- name: PreviousDeploy :one
SELECT id, project, commit_sha, "trigger", images, snapshot_id, restored_id, undoes, result, error, summary, started_at, finished_at, before_id, parts FROM deploys WHERE project = ? AND id < ? ORDER BY id DESC LIMIT 1
`

type PreviousDeployParams struct {
	Project string `json:"project"`
	ID      int64  `json:"id"`
}

func (q *Queries) PreviousDeploy(ctx context.Context, arg PreviousDeployParams) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, previousDeploy, arg.Project, arg.ID)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.CommitSha,
		&i.Trigger,
		&i.Images,
		&i.SnapshotID,
		&i.RestoredID,
		&i.Undoes,
		&i.Result,
		&i.Error,
		&i.Summary,
		&i.StartedAt,
		&i.FinishedAt,
		&i.BeforeID,
		&i.Parts,
	)
	return i, err
}

const putPin = `-- name: PutPin :exec
INSERT INTO pins (project, service, image, digest, compose_image, deploy_id, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (project, service) DO UPDATE SET image = excluded.image, digest = excluded.digest, compose_image = excluded.compose_image,
    deploy_id = excluded.deploy_id, created_at = excluded.created_at
`

type PutPinParams struct {
	Project      string `json:"project"`
	Service      string `json:"service"`
	Image        string `json:"image"`
	Digest       string `json:"digest"`
	ComposeImage string `json:"compose_image"`
	DeployID     int64  `json:"deploy_id"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) PutPin(ctx context.Context, arg PutPinParams) error {
	_, err := q.db.ExecContext(ctx, putPin,
		arg.Project,
		arg.Service,
		arg.Image,
		arg.Digest,
		arg.ComposeImage,
		arg.DeployID,
		arg.CreatedAt,
	)
	return err
}

const putPreview = `-- name: PutPreview :exec
INSERT INTO previews (project, name, ref, commit_sha, images, services, snapshot_id, deploy_id, data, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (project, name) DO UPDATE SET ref = excluded.ref, commit_sha = excluded.commit_sha, images = excluded.images, services = excluded.services, updated_at = excluded.updated_at
`

type PutPreviewParams struct {
	Project    string `json:"project"`
	Name       string `json:"name"`
	Ref        string `json:"ref"`
	CommitSha  string `json:"commit_sha"`
	Images     string `json:"images"`
	Services   string `json:"services"`
	SnapshotID int64  `json:"snapshot_id"`
	DeployID   int64  `json:"deploy_id"`
	Data       string `json:"data"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

// creates a preview or updates it; created_at, snapshot_id, deploy_id and data belong to its creation
func (q *Queries) PutPreview(ctx context.Context, arg PutPreviewParams) error {
	_, err := q.db.ExecContext(ctx, putPreview,
		arg.Project,
		arg.Name,
		arg.Ref,
		arg.CommitSha,
		arg.Images,
		arg.Services,
		arg.SnapshotID,
		arg.DeployID,
		arg.Data,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const recentDeployImages = `-- name: RecentDeployImages :many
SELECT images FROM deploys d
WHERE (SELECT count(*) FROM deploys x WHERE x.project = d.project AND x.id > d.id) < CAST(?1 AS INTEGER)
`

// the images of the newest `keep` deploys of every project (registry gc keeps them)
func (q *Queries) RecentDeployImages(ctx context.Context, keep int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, recentDeployImages, keep)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var images string
		if err := rows.Scan(&images); err != nil {
			return nil, err
		}
		items = append(items, images)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEnv = `-- name: SetEnv :exec
INSERT INTO env (project, key, value, updated_at) VALUES (?, ?, ?, ?)
ON CONFLICT (project, key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type SetEnvParams struct {
	Project   string `json:"project"`
	Key       string `json:"key"`
	Value     []byte `json:"value"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) SetEnv(ctx context.Context, arg SetEnvParams) error {
	_, err := q.db.ExecContext(ctx, setEnv,
		arg.Project,
		arg.Key,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}

const setMeta = `-- name: SetMeta :exec
INSERT INTO meta (key, value) VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type SetMetaParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetMeta(ctx context.Context, arg SetMetaParams) error {
	_, err := q.db.ExecContext(ctx, setMeta, arg.Key, arg.Value)
	return err
}

const setProjectApplied = `-- name: SetProjectApplied :exec
INSERT INTO projects (path, commit_sha, applied_at) VALUES (?, ?, ?)
ON CONFLICT (path) DO UPDATE SET commit_sha = excluded.commit_sha, applied_at = excluded.applied_at
`

type SetProjectAppliedParams struct {
	Path      string `json:"path"`
	CommitSha string `json:"commit_sha"`
	AppliedAt int64  `json:"applied_at"`
}

func (q *Queries) SetProjectApplied(ctx context.Context, arg SetProjectAppliedParams) error {
	_, err := q.db.ExecContext(ctx, setProjectApplied, arg.Path, arg.CommitSha, arg.AppliedAt)
	return err
}

const setProjectDisabled = `-- name: SetProjectDisabled :exec
INSERT INTO projects (path, disabled) VALUES (?, ?)
ON CONFLICT (path) DO UPDATE SET disabled = excluded.disabled
`

type SetProjectDisabledParams struct {
	Path     string `json:"path"`
	Disabled bool   `json:"disabled"`
}

func (q *Queries) SetProjectDisabled(ctx context.Context, arg SetProjectDisabledParams) error {
	_, err := q.db.ExecContext(ctx, setProjectDisabled, arg.Path, arg.Disabled)
	return err
}

const setProjectLimits = `-- name: SetProjectLimits :exec
INSERT INTO projects (path, limits) VALUES (?, ?)
ON CONFLICT (path) DO UPDATE SET limits = excluded.limits
`

type SetProjectLimitsParams struct {
	Path   string `json:"path"`
	Limits string `json:"limits"`
}

func (q *Queries) SetProjectLimits(ctx context.Context, arg SetProjectLimitsParams) error {
	_, err := q.db.ExecContext(ctx, setProjectLimits, arg.Path, arg.Limits)
	return err
}

const unsetEnv = `-- name: UnsetEnv :exec
DELETE FROM env WHERE project = ? AND key = ?
`

type UnsetEnvParams struct {
	Project string `json:"project"`
	Key     string `json:"key"`
}

func (q *Queries) UnsetEnv(ctx context.Context, arg UnsetEnvParams) error {
	_, err := q.db.ExecContext(ctx, unsetEnv, arg.Project, arg.Key)
	return err
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users SET role = ?1, global = ?2,
    secret = CASE WHEN ?3 = '' THEN secret ELSE ?3 END
WHERE name = ?4
`

type UpdateUserParams struct {
	Role   string      `json:"role"`
	Global bool        `json:"global"`
	Secret interface{} `json:"secret"`
	Name   string      `json:"name"`
}

// an empty secret keeps the current one
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUser,
		arg.Role,
		arg.Global,
		arg.Secret,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
